### ISSUE TITLE
Burst not found MSVC installation

### ISSUE THREAD

**Issue by LucBRG** [Unity-Technologies/multiplayer#12]
Hello,

When I trying to export this project from Mac to Windows, I got an error but no problem when I exported for MacOS.

See here:
https://forum.unity.com/threads/burst-not-found-msvc-installation.594496/

Thanks

**Comment by zhuchun** [comment]
Hello, it's me again :) How about switching the scripting backgrounds from IL2CPP to mono? I didn't try it, but it should be fine, mono is slower though.

**Comment by timj-unity** [comment]
Burst support for cross compilation is not a multiplayer issue
