### ISSUE TITLE
Sample Request: Split ECS into separate server and client projects

### ISSUE THREAD

**Issue by IT-LCEC** [Unity-Technologies/multiplayer#14]
Thanks for the dedicated work on the project. It would be great to get an example of the ECS broken into two projects; client and server. I am already doing this and happy to share, but not sure I got it right. 

Might also be helpful to show how different data packet types should be routed properly to take advantage of ECS/Jobs once the packet is received by the server. And lastly, from a security perspective, how does the server know the client is permitted to communicate? 

I am happy to help on this request but may need someone to proof my work. 

Thanks

**Comment by asyasmi** [comment]
Hi @IT-LCEC 

Sorry for such a long response from us.  My name is Anastasia, I’m a software developer in test engineer in Networking team. As a part of old issues review and closure procedure, I’ve looked through this issue. 

> ECS broken into two projects
We are working on samples, and I will add your request to our list also. As an example of usage you can check https://github.com/Unity-Technologies/DOTSSample project also, it contains example you might be looking for. 

>how different data packet types should be routed properly to take advantage of ECS/Jobs once the packet is received by the server
This is definitely a good point to take a look at in tutorial, and it's already one of the first in the list to be covered. 

> how does the server know the client is permitted to communicate
Security implementation is going to be build up into DOTS core and to the netcode in upcoming versions. 


Closing this issue, but in case of any additional questions/issues - please file a bug using Unity Bug reporter.
Thanks, Anastasia
