### ISSUE TITLE
SQPDriver throw an exception when import

### ISSUE THREAD

**Issue by zhuchun** [Unity-Technologies/multiplayer#15]
~~Hi, I'm new here and following the installation, the compiler throws an exception~~

~~>Assets\ServerQueryProtocol\SQPDriver.cs(22,13): error CS0103: The name 'CommandLine' does not exist in the current context~~

~~It looks like that a util script named `CommandLine` is missing?~~

Hi, please add a line like "Also copy CommandLine script from the asset folder to your new project" into the installation, otherwise the compiller will thorw an error.

**Comment by gegagome** [comment]
OK, how is this issue solved?

**Comment by timj-unity** [comment]
SQP has been removed from this repo and will be a package which removes the need to copy anything
