### ISSUE TITLE
Time out info in documentation

### ISSUE THREAD

**Issue by Epicguru** [Unity-Technologies/multiplayer#16]
Hey, I was hoping that somewhere in the basic tutorials (basic client / server setup) it could be mentioned about having to receive data from the server to avoid timing out and disconnecting. For example, mention that the server should send a ping message every second just to keep the client connection alive. Even if the code to do this isn't explicitly written, it would be nice for it to be mentioned somewhere to avoid confusion as to why the client seemingly randomly disconnects when using the tutorial code. Thanks.

**Comment by Chexxxor** [comment]
I wanna emphasize the importance of this. While I tried to solve this issue myself, I've met some struggles, one of which I haven't figured out yet is that timeouts seems to have different behaviour if I run two Unity Editors on the same computer and connect them with my server-/client-behaviour scripts. However if I run my server online, and connect the client from another machine I don't have the same issue. Thus I believe ANY insight into timeouts in the documentation would be very useful when trying to understand the unwanted disconnections.

**Comment by pencilking2002** [comment]
Yes, I would also appreciate more info on keeping connections alive and at what point/reason they could disconnect and how to account for this.

**Comment by Skjalgsm** [comment]
I wouldn't hold my breath, at this point I doubt we'll see this updated and
Im suspecting this project is dead. No issues are responded to and PR's are
left to rot. On the forum they promised an update in December, then in
January and now its March in just a day.

If I were you, I'd spend my time on other multiplayer projects instead and
maybe just use this as a learning exercise to read how to start making your
own networking code if you like to do that. One valuable lesson to learn
from this is to not start using brand new things, even if it is from Unity
itself.

**Comment by pencilking2002** [comment]
Ooof I really hope that's not the case. It does work...my team has been able to use it on a real project.

**Comment by Skjalgsm** [comment]
Yeah me too, and it’s a good thing they provided the source

ons. 27. feb. 2019 kl. 15:51 skrev pencilking2002 <notifications@github.com

**Comment by Epicguru** [comment]
It has been so long since this project has been updated that I have moved my code over to Lidgren, which basically does the same thing as this (in its current state) but better and easier to use.

**Comment by asyasmi** [comment]
Hi to all, 

Sorry for such a long response from us. My name is Anastasia, I’m a software developer in test engineer in Networking team. As a part of the old issues review and closure procedure, I’ve looked through this issue. 

The project is in development and we're continuing to publish new packages versions, as you might have noticed, and sample project is also being updated as well, unfortunately not that often in the public repository. 

We're just stepping into the phase of documentation update now, so I'll add your request to it. 

Closing this issue, but in case of any additional questions/issues - please file a bug using Unity Bug reporter.
Thanks, Anastasia
