### ISSUE TITLE
Installation guide: <RI.Hid> Failed to create device file

### ISSUE THREAD

**Issue by johanhelsing** [Unity-Technologies/multiplayer#19]
I got this error after following the installation guide:

```
<RI.Hid> Failed to create device file:
 20 Prosessen får ikke tilgang til filen fordi den brukes av en annen prosess.
```

The last line means somethign along the lines of: The process does not get access to the file because it's used by another process.

Unity 2018.3.4f1 on Windows

**Comment by TaynaCT** [comment]
same here, I'm having this problem after my app is open for a while. My app is running on a windows 10 with touch input.

```
<RI.Hid> Failed to create device file:
 20 The process cannot access the file because it is being used by another process.
```

**Comment by timj-unity** [comment]
Ri = RawInput. This is related to the input system and not multiplayer/transport.
