### ISSUE TITLE
workflow-client-server.md uses NativeList, but doesn't say where to get it

### ISSUE THREAD

**Issue by johanhelsing** [Unity-Technologies/multiplayer#20]

**Comment by zhuchun** [comment]
Isn't it in the entities package?

**Comment by johanhelsing** [comment]
Yes, I think so, but the bug is that the guide doesn't say that you should install it. So you would get compile errors when following it.

**Comment by timj-unity** [comment]
NativeList lives in com.unity.collection and the transport has a dependency on that package. So if you have the transport you will also have NativeList without doing anything special
