### ISSUE TITLE
ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by virgilcwylie** [Unity-Technologies/multiplayer#22]
So I guess i am able to send the data from the server easily. Server sends out 1700+ bytes of data. When I am trying to read it throws me error. " argumentOutOfRangeException: Specified argument was out of the range of valid values".
I tried going in deep and saw something restricting reading of data. Why is it that I can write this amount but can't read?? 
Any help would be highly appreciated.

**Comment by virgilcwylie** [comment]
Then I also get weird error like this,
Resetting event queue with pending events (Count=3, ConnectionID=0) Listening: False

**Comment by OJuergen** [comment]
The latter usually means that you did not pop all received network events and some are discarded

**Comment by virgilcwylie** [comment]
Thanks for comment. Turned out the MTU is 1400 bytes so it was resetting the queue. In mean while I have been trying to learn this new technology. I came across that there is a queue of network events. And if the queue size is exceeded it resets it. I was wondering how I could control the queue like you are said “did not pop all”. Is there any example to manually manage the queue of networks events?

**Comment by timj-unity** [comment]
The out of range errors have been fixed, we have a change on a future branch which makes it impossible to send MTU. There is no manual queue management, when you call ScheduleUpdate it will copy all messages to a queue - you need to pop all of them before you call ScheduleUpdate again or you are loosing messages which results in the error mentioned

**Comment by valkyrienyanko** [comment]
" you need to pop all of them before you call ScheduleUpdate again or you are loosing messages which results in the error mentioned "

How do you do that exactly?

**Comment by OJuergen** [comment]
By implementing a loop that calls NetworkConnection.PopEvent() until it
returns NetworkEvent.Type.Empty

Am Sa., 2. Mai 2020 um 05:44 Uhr schrieb valkyrienyanko <
notifications@github.com>:
