### ISSUE TITLE
Divide by zero error?

### ISSUE THREAD

**Issue by kursadacar** [Unity-Technologies/multiplayer#27]
The server and client was working with the initial release. I kind of upgraded by changing UdpCNetworkDriver to new UdpNetworkDriver and IPEndPoints to NetworkEndpoints. But when i try to connect, client gives this error:

_DivideByZeroException: Attempted to divide by zero.
Unity.Networking.Transport.Utilities.ReliableUtility.Release (Unity.Collections.NativeSlice`1[T] self, System.Int32 start_sequence, System.Int32 count)_ 

The fuction i use to connect is this:
```
    public void ConnectToLocalhost()
    {
        var endpoint = NetworkEndPoint.Parse("127.0.0.1", 9000);
        endpoint.Port = 9000;
        m_Connection = m_Driver.Connect(endpoint);
    }
```
Error is on the line :

>         m_Connection = m_Driver.Connect(endpoint);

PS: I set up a debug message on the server that notifies me when a new connection is established. Connection message appears on server but it seems to receive no data.

**Comment by Opeth001** [comment]
were you able to solve this problem ?

**Comment by kgc00** [comment]
changed the `UdpNetworkDriver` assignment in ClientBehaviour.cs:

`m_Driver = new UdpNetworkDriver (new INetworkParameter[0]);` changed to 
`m_Driver = new UdpNetworkDriver (new ReliableUtility.Parameters { WindowSize = 32 });`.

Fixed the error for me.  (ServerBehaviour was using ReliableUtility already)

**Comment by Opeth001** [comment]
i fixed it the same way ^^
