### ISSUE TITLE
32 packet limit with reliable pipeline

### ISSUE THREAD

**Issue by bryanfiles** [Unity-Technologies/multiplayer#29]
Even after increasing WindowSize, the reliable pipeline silently fails to send packets with only 32 inflight.  While that is marginal during smooth network operation, it instantly becomes a problem when there is a hiccup.

It seems to me that one should be able to count on messages getting delivered or notification that the connection is bad.  Is such functionality planned for the Unity Transport Package?

**Comment by TomasRiker** [comment]
The documentation mentions that 32 is the maximum. I agree there should at least be a warning if one tries to set it to a higher value.

**Comment by alfiare** [comment]
Is there any plan for the maximum of 32 to be either raised or removed and just allow it to be set?

**Comment by asyasmi** [comment]
Hi @bryanfiles, @TomasRiker and @alfiare 

Sorry for such a long response from us.  My name is Anastasia, I’m software developer in test engineer in Networking team. As a part of old issues review and closure procedure, I’ve looked through this issue. 

On current stage of development, WindowSize is set to 32 deliberately and thus it allows not to overflow the queue with packages inflight. 
Regarding @TomasRiker question, we’ve added warnings on adding WindowSize exceeding maximum value, some of those are covered in ReliablePipelineTests in the latest packages release   ``` netcode: 0.2.0-preview.5 ```
```transport: 0.3.1-preview.4 ```. 

Closing this issue, but in case of any additional questions/issues - please file a bug using Unity Bug reporter.
Thanks, Anastasia
