### ISSUE TITLE
Error on Receive 10040

### ISSUE THREAD

**Issue by kursadacar** [Unity-Technologies/multiplayer#31]
Hi, my client and server works fine on 2019.1.0f2.
I am trying to send current map state to the new client as they connect, it also worked fine until i increased the number of map objects that i send thorough a list.(a list of a class that holds instance id position rotation etc.).
I am guessing this is an issue with the max packet size limit. Since according to google error code 10040 is related to oversized package.
Can you offer me a solution where i can increase package size? I am using package this big only when a new player connected, and i am guessing it shouldnt be more than 2 kilobytes.

**Comment by Chexxxor** [comment]
Yes, you will get the error code 10040 when sending a packet that exceeds one of the buffer sizes internal to Winsock 2.0. When using Unity's transport package, one should not send packets larger than 1400 bytes, subtract the size of headers depending on which pipeline you're using. (Below).

> I am using package this big only when a new player connected, and i am guessing it shouldnt be more than 2 kilobytes.

Not a solution, but the [MTU](https://en.wikipedia.org/wiki/Maximum_transmission_unit) for a UDP payload is set to 1400 bytes [here](https://github.com/Unity-Technologies/multiplayer/blob/master/com.unity.transport/Runtime/NetworkParams.cs). This is a value set by Unity, probably to have some margin below the typical [1472](https://stackoverflow.com/questions/3928766/how-big-is-an-ip-packet-frame-including-headers) bytes of UDP payload commonly used to avoid [fragmentation](https://en.m.wikipedia.org/wiki/IP_fragmentation) (as it impacts real-time games). Of the 1400 you have to account for the header data added by the transport package upon sending the data, which is 4 bytes [(UdpCHeader)](https://github.com/Unity-Technologies/multiplayer/blob/master/com.unity.transport/Runtime/NetworkProtocols.cs) when using the unreliable pipeline and 16 bytes (UdpCHeader + [PacketHeader)](https://github.com/Unity-Technologies/multiplayer/blob/master/com.unity.transport/Runtime/Pipelines/ReliableUtility.cs) when using the reliable one if I'm not mistaken.

**Comment by kursadacar** [comment]
Thanks for clarifying that. I am now sending map data partially and combine data at client when finished. That seems to work fine :)

**Comment by timj-unity** [comment]
Sending it as partial updates is the way to go. We might add a fragmentation pipeline to allow you to do that in the future. The behavior has changed to give an error when sending messages larger than MTU on an internal development branch (unsure if it landed before we pushed latest but it will be fixed)
