### ISSUE TITLE
Ghost Quaternion Getter Issue (when not toggled 2d)

### ISSUE THREAD

**Issue by churbis** [Unity-Technologies/multiplayer#34]
The code that gets generated from using GhostSnapshotValue.cs for a quaternion (that isn't a 2d one -- those generate fine as in the Asteroids demo -- will throw an "error CS0019: Operator '*' cannot be applied to operands of type 'quaternion' and 'float'"

` private const string k_SnapshotQuaternionFieldGetSetTemplate = @"    public quaternion Get$(GHOSTFIELD)()
    {
        return new quaternion($(GHOSTFIELD)X, $(GHOSTFIELD)Y, $(GHOSTFIELD)Z, $(GHOSTFIELD)W) * $(GHOSTDEQUANT);
    }
    public void Set$(GHOSTFIELD)(quaternion q)
    {
        $(GHOSTFIELD)X = (int)(q.value.x * $(GHOSTQUANT));
        $(GHOSTFIELD)Y = (int)(q.value.y * $(GHOSTQUANT));
        $(GHOSTFIELD)Z = (int)(q.value.z * $(GHOSTQUANT));
        $(GHOSTFIELD)W = (int)(q.value.w * $(GHOSTQUANT));
    }
";`

**Comment by timj-unity** [comment]
This is fixed in the new package version of netcode, get scales x, y, z and w before constructing the quaternion
`    public quaternion Get__GHOST_FIELD_NAME__()
    {
        return new quaternion(__GHOST_FIELD_NAME__X * __GHOST_DEQUANTIZE_SCALE__, __GHOST_FIELD_NAME__Y * __GHOST_DEQUANTIZE_SCALE__, __GHOST_FIELD_NAME__Z * __GHOST_DEQUANTIZE_SCALE__, __GHOST_FIELD_NAME__W * __GHOST_DEQUANTIZE_SCALE__);
    }`
