### ISSUE TITLE
Error while running Asteroids sample : [InvalidOperationException: Cannot send data while connecting]

### ISSUE THREAD

**Issue by ndp1100** [Unity-Technologies/multiplayer#35]
I tried to run asteroids on my editor, but got error like below :

> InvalidOperationException: Cannot send data while connecting
Unity.Networking.Transport.GenericNetworkDriver`2+Concurrent[T,TNetworkPipelineStageCollection].Send (Unity.Networking.Transport.NetworkConnection id, Unity.Networking.Transport.network_iovec* dataIov, System.Int32 dataIovLen) (at D:/Working/PhuongND/NetCodeLearningProject/com.unity.transport/Runtime/NetworkDriver.cs:150)
Unity.Networking.Transport.NetworkPipelineProcessor`1+Concurrent[TNetworkPipelineStageCollection].ProcessPipelineSend[T] (T driver, System.Int32 startStage, Unity.Networking.Transport.NetworkPipeline pipeline, Unity.Networking.Transport.NetworkConnection connection, Unity.Collections.NativeSlice`1[T] payloadBuffer, Unity.Collections.NativeList`1[T] currentUpdates) (at D:/Working/PhuongND/NetCodeLearningProject/com.unity.transport/Runtime/NetworkPipeline.cs:265)
Unity.Networking.Transport.NetworkPipelineProcessor`1+Concurrent[TNetworkPipelineStageCollection].Send[T] (T driver, Unity.Networking.Transport.NetworkPipeline pipeline, Unity.Networking.Transport.NetworkConnection connection, Unity.Collections.NativeSlice`1[T] payloadData) (at D:/Working/PhuongND/NetCodeLearningProject/com.unity.transport/Runtime/NetworkPipeline.cs:156)
Unity.Networking.Transport.GenericNetworkDriver`2+Concurrent[T,TNetworkPipelineStageCollection].Send (Unity.Networking.Transport.NetworkPipeline pipe, Unity.Networking.Transport.NetworkConnection id, System.IntPtr data, System.Int32 len) (at D:/Working/PhuongND/NetCodeLearningProject/com.unity.transport/Runtime/NetworkDriver.cs:96)
Unity.Networking.Transport.GenericNetworkDriver`2+Concurrent[T,TNetworkPipelineStageCollection].Send (Unity.Networking.Transport.NetworkPipeline pipe, Unity.Networking.Transport.NetworkConnection id, Unity.Networking.Transport.DataStreamWriter strm) (at D:/Working/PhuongND/NetCodeLearningProject/com.unity.transport/Runtime/NetworkDriver.cs:79)
Unity.Networking.Transport.UdpNetworkDriver+Concurrent.Send (Unity.Networking.Transport.NetworkPipeline pipe, Unity.Networking.Transport.NetworkConnection id, Unity.Networking.Transport.DataStreamWriter strm) (at D:/Working/PhuongND/NetCodeLearningProject/com.unity.transport/Runtime/NetworkDriver.cs:1178)
CommandSendSystem`1+CommandSendJob[TCommandData].Execute (Unity.Entities.Entity entity, System.Int32 index, CommandTargetComponent& state) (at Assets/NetCode/Command/CommandSendSystem.cs:44)
Unity.Entities.JobForEachExtensions+JobStruct_Process_EC`2[T,T0].ExecuteChunk (Unity.Entities.JobForEachExtensions+JobStruct_Process_EC`2[T,T0]& jobData, System.IntPtr bufferRangePatchData, System.Int32 begin, System.Int32 end, Unity.Entities.ArchetypeChunk* chunks, System.Int32* entityIndices) (at Library/PackageCache/com.unity.entities@0.0.12-preview.33/Unity.Entities/IJobForEach.gen.cs:1683)
Unity.Entities.JobForEachExtensions+JobStruct_Process_EC`2[T,T0].Execute (Unity.Entities.JobForEachExtensions+JobStruct_Process_EC`2[T,T0]& jobData, System.IntPtr additionalPtr, System.IntPtr bufferRangePatchData, Unity.Jobs.LowLevel.Unsafe.JobRanges& ranges, System.Int32 jobIndex) (at Library/PackageCache/com.unity.entities@0.0.12-preview.33/Unity.Entities/IJobForEach.gen.cs:1660)

**Comment by Tom60chat** [comment]
Same

**Comment by timj-unity** [comment]
The CommandSendSystem will not send anything until the connection is established and set to in-game with the new version released today
