### ISSUE TITLE
DllImport of `network.bindings` fails on Linux x64

### ISSUE THREAD

**Issue by garyttierney** [Unity-Technologies/multiplayer#36]
On Fedora 30 attempting to use the native `libnetwork.bindings.so` library fails, with an error on resolving a DLL named `network.bindings`. It looked to me like the dot suffix was confusing the loader, so I changed the Makefile to output `libnetwork-bindings.so` instead and the import successfully resolves.

I'm not sure that's the correct fix for the underlying problem, but I've attached a patch with the changes (and can open a pull request) if that works.

Patch: https://gist.github.com/garyttierney/f565a959101d68e24d667c43eeb714dd

**Comment by asyasmi** [comment]
Hi @garyttierney 

Sorry for such a long response from us.  My name is Anastasia, I’m software developer in test engineer in Networking team. As a part of old issues review and closure procedure, I’ve looked through this issue. 

For our x64 Ubuntu we use 
```
clang -fPIC -Wall -Wextra -std=gnu99 -g -o network.bindings/build/network.bindings/obj/network.bindings.o -c source/network.bindings.c

clang -Wall -Wextra -std=gnu99 -g -shared -Wl,-soname,libnetwork.bindings.so network.bindings/build/network.bindings/obj/network.bindings.o -o bin/libnetwork.bindings.so
```

and then copy all built `network.bindings.*` files to `/com.unity.transport/Runtime/Bindings`

Hope that helps. Closing this issue, but in case of any additional questions/issues - please file a bug using Unity Bug reporter.
Thanks, Anastasia
