### ISSUE TITLE
Latency? (compared to UNet)

### ISSUE THREAD

**Issue by ckcollab** [Unity-Technologies/multiplayer#38]
First of all: thanks for all of the hard work on this and releasing such concise documentation! It's a pleasure to see the new docs with plenty of code samples tying things together. We've had a good time building on top of UNet but are experiencing some growing pains with latency.

Apologies if this is asked often, but: is this library much faster than UNet? Fundamentally this library may be similar design wise to UNet and this is a dumb question! :)

**Comment by WAYNGROUP** [comment]
Hi from what i understand from this post : 
https://blogs.unity3d.com/2019/06/13/navigating-unitys-multiplayer-netcode-transition/

Yes, the new way should get better latency as it is not peer to peer (like UNet) but disigned for Dedicated Game Server.

**Comment by timj-unity** [comment]
Unet was a p2p solution going through a relay server which caused lots of latency. The new netcode is a dedicated server model which means we do not need a relay. We are also doing client prediction which reduces perceived latency to basically nothing.
