### ISSUE TITLE
Multiple sending/receiving channels

### ISSUE THREAD

**Issue by mnarimani** [Unity-Technologies/multiplayer#39]
Is it possible to have two channels? Specifically an unreliable and a reliable unordered channel?

**Comment by Chexxxor** [comment]
Also wondering this. To add to the issue, I tried creating two different pipelines, but only the last one seemed to work at all times. I suppose a workaround would be two different connections all together but that seems like a tedious workaround and extra code maintenance.

**Comment by timj-unity** [comment]
It is possible to have multiple pipelines and send with both of them, the netcode package does this for mixing reliable rpcs messages and unreliable snapshot messages in the same connection.
To do so you must create both pipelines in the same order on both sides, and you need to specify which pipeline to use for each send.
The pipeline will use the same pipeline index, which is which pipeline in the creation order it was, to decode the message.
