### ISSUE TITLE
UdpCNetworkDriver working only with Local Ip Address

### ISSUE THREAD

**Issue by Opeth001** [Unity-Technologies/multiplayer#4]
Hello,
im trying to use Unity.Networking.Transport and  try the speed on my dedicated server and build my Server logic on TOP of this project but when i change the 192.168.1.2 to My IP Address nothing works anymore without any Error.
i tried to open my port 9000 from the Firewall but still not working.

 var MyIpAdressParsed = IPAddress.Parse("192.168.1.2");
 var endpoint = new IPEndPoint(MyIpAdressParsed, 9000);
 m_Connection[0] = m_Driver.Connect(endpoint);
 
any help or suggestions will be appreciated.
Thank you

**Comment by Jaden-Giordano** [comment]
Have you tried using `IPAddress.Any`? This binds to all on your host making available both locally and externally (assuming your ports are forwarded).

**Comment by Opeth001** [comment]
the IPAddress.Any should be used in server side not client side no?
because i have to specify the host IP Address

**Comment by pencilking2002** [comment]
Not sure if this helps but so far, I've been able two connect two devices that are on the same wifi network. I'm able to connect my android device(client) to a server (mac computer). Here's my client code:

```
public UdpCNetworkDriver m_Driver;
public NetworkConnection m_Connection;
public static IPAddress ipAddres = IPAddress.Parse("my-local-ip-address-in-my-wifi-network");
public int portNum = 9000;

public void ConnectToServer()
{      
       var endpoint = new IPEndPoint(ipAddres, portNum);
       m_Connection = m_Driver.Connect(endpoint);
} 
```
To get my IP address, I went to this site:https://www.whatismyip.com/ and I used the ip address labeled "Your Local IP is"

**Comment by Opeth001** [comment]
hi @pencilking2002 
cause they are both connected to the same router so using the same IP Address.
but try to connected via 2 diffrent Routers or 1 via 3/4G and the 2 via wifi and it will not work :(

**Comment by pencilking2002** [comment]
oh man, that's disappointing. Do you know if Unity has been able to do this with their FPS sample game?

**Comment by Opeth001** [comment]
i think they are using a  more advanced lib, if you are looking to use a good multithreaded safe  and open source Networking lib try Forge Networking Remastered it's just awesome !

**Comment by Opeth001** [comment]
@pencilking2002
 your welcome ;)
if you have question join their Discord Servers: https://discordapp.com/invite/yzZwEYm
Enjoy!

**Comment by Opeth001** [comment]
hi @timj-unity  ^_^
i already tried diffrent Libs and servers on my VPS and everything Works except UnityTechnologies/multiplayer.
can you please share any example  trying to connect to a specific IP address , so i can try it using my vps.
 this issue is made a long time ago so i dont use this lib anymore :(.
but ill rly  appreciate to use it again, cause im trying to make my game using everything via ECS ( hybred & pure ) 
Thank you.

**Comment by timj-unity** [comment]
The most well tested sample doing this is the ping sample in the repo. We set a ServerEndPoint in https://github.com/Unity-Technologies/multiplayer/blob/master/sampleproject/Assets/Samples/Ping/PingClientUIBehaviour.cs and use it to connect to a server in https://github.com/Unity-Technologies/multiplayer/blob/master/sampleproject/Assets/Samples/Ping/PingClientBehaviour.cs . The server does not have to do anything special apart from binding to "any", and like I said - it also need to have a public ip.
