### ISSUE TITLE
Error Code: 10049

### ISSUE THREAD

**Issue by RealZinex** [Unity-Technologies/multiplayer#40]
When trying to bind to my public IP it fails and returns error 10049. Have it running and binding find to loopback (127.0.0.1:9999) just fine and is how I have been doing my testing and building around the UNET2 platform. Tried on a few machines and different internet connections. 

Can't seem to find a place where error codes are listed or explained so if anyone can point me in the right direction id be very grateful! :P 

network.bindings.cs Line: 86
'''
[DllImport(m_DllName, CallingConvention = CallingConvention.Cdecl)]
public static extern int network_create_and_bind(ref long socket_handle, ref NetworkEndPoint address, ref int errorcode);
'''

Is where the error code is coming from. 

Thanks 
Z

**Comment by timj-unity** [comment]
The error code is coming directly from the system. In your case it looks like windows, so https://docs.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2 .
10049 means the address is invalid
