### ISSUE TITLE
Entity Queries in `AfterSimulationInterpolationSystem` are wrong

### ISSUE THREAD

**Issue by hwei** [Unity-Technologies/multiplayer#42]
In entity query `positionInterpolationGroup`, the `CurrentSimulatedPosition` is defined as `ComponentType.ReadOnly<CurrentSimulatedPosition>`.
But the `UpdateCurrentPosJob` will write into `CurrentSimulatedPosition`.

All the 4 queries in this `AfterSimulationInterpolationSystem` have similar problems.

**Comment by timj-unity** [comment]
Thanks, will be fixed in the next release
