### ISSUE TITLE
The Unity Transport manual is outdated

### ISSUE THREAD

**Issue by alexddhuang** [Unity-Technologies/multiplayer#44]
I followed the Unity Transport manual to build a simple client-server project, but I finally got some errors that were due to the APIs of `com.unity.transport` was updated.

I think it would be more friendly if the documents keep updating.

**Comment by mfitzer** [comment]
@alexddhuang I was able to create a working version of the client server sample with the updated code here: [https://github.com/mfitzer/Real-time_Multiplayer_Test](https://github.com/mfitzer/Real-time_Multiplayer_Test). I also added comments to outline what is going on based on the manual.

**Comment by timj-unity** [comment]
I verified most of the samples and they seem to work fine now
