### ISSUE TITLE
Unity Terrain not shown.

### ISSUE THREAD

**Issue by maltesermailo** [Unity-Technologies/multiplayer#45]
I've followed the quickstart guide for the NetCode. I got everything setup. Cube and Plane spawns, but when I want to add a Unity Terrain in Mixed World it doesn't spawn? What am I doing wrong?

**Comment by timj-unity** [comment]
Terrain does not support conversion to entities as far as I know. That means that the terrain will not exist after the game objects are gone. To add terrain you need to add it as usual game objects without any ConvertToClientServerEntity, which will make your game hybrid.
