### ISSUE TITLE
Error after I added the package.

### ISSUE THREAD

**Issue by AugustToko** [Unity-Technologies/multiplayer#46]
Library\PackageCache\com.unity.burst@1.0.4\Editor\BurstAotCompiler.cs(638,32): error CS7036: There is no argument given that corresponds to the required formal parameter 'exceptionType' of 'BuildReport.AddMessage(LogType, string, string)'

<hr/>

            private static void RunProgram(
              Program p,
              string exe,
              string args,
              string workingDirectory,
              CompilerOutputParserBase parser,
              BuildReport report)
            {
                Stopwatch stopwatch = new Stopwatch();
                stopwatch.Start();
                using (p)
                {
                    p.GetProcessStartInfo().WorkingDirectory = workingDirectory;
                    p.Start();
                    p.WaitForExit();
                    stopwatch.Stop();

                    Console.WriteLine("{0} exited after {1} ms.", (object)exe, (object)stopwatch.ElapsedMilliseconds);
                    IEnumerable<UnityEditor.Scripting.Compilers.CompilerMessage> compilerMessages = null;
                    string[] errorOutput = p.GetErrorOutput();
                    string[] standardOutput = p.GetStandardOutput();
                    if (parser != null)
                    {
                        compilerMessages = parser.Parse(errorOutput, standardOutput, true, "n/a (burst)");
                    }

                    var errorMessageBuilder = new StringBuilder();
                    if (p.ExitCode != 0)
                    {
                        if (compilerMessages != null)
                        {
                            foreach (UnityEditor.Scripting.Compilers.CompilerMessage compilerMessage in compilerMessages)
                            {
                                Debug.LogPlayerBuildError(compilerMessage.message, compilerMessage.file, compilerMessage.line, compilerMessage.column);
                            }
                        }

                        // We try to output the version in the heading error if we can
                        var matchVersion = MatchVersion.Match(exe);
                        errorMessageBuilder.Append(matchVersion.Success ?
                            "Burst compiler (" + matchVersion.Groups[1].Value + ") failed running" :
                            "Burst compiler failed running");
                        errorMessageBuilder.AppendLine();
                        errorMessageBuilder.AppendLine();
                        // Don't output the path if we are not burst-debugging or the exe exist
                        if (BurstLoader.IsDebugging || !File.Exists(exe))
                        {
                            errorMessageBuilder.Append(exe).Append(" ").Append(args);
                            errorMessageBuilder.AppendLine();
                            errorMessageBuilder.AppendLine();
                        }

                        errorMessageBuilder.AppendLine("stdout:");
                        foreach (string str in standardOutput)
                            errorMessageBuilder.AppendLine(str);
                        errorMessageBuilder.AppendLine("stderr:");
                        foreach (string str in errorOutput)
                            errorMessageBuilder.AppendLine(str);

                        // We don't use Debug.LogError as it displays a stacktrace that we really don't want to pollute our message output
                        //report.AddMessage(LogType.Error, errorMessageBuilder.ToString());
                        Debug.LogPlayerBuildError(errorMessageBuilder.ToString(), "unknown", 0, 0);

                        // We report the error to the build player but it seems that it is not correctly reported.
                        // In Editor\Src\BuildPipeline\BuildPlayer.cpp
                        //    if (report.GetSuccess())
                        //    {
                        //        DisplayProgressNotification("Build Successful", "");
                        //    }
                        //
                        //    report.UnregisterForLogMessages();
                        //    report.EndBuildStep(buildStepToken);
                        //    report.UpdateSummary();
                        //
                        // Actually report.GetSuccess() should go after the last UpdateSummary()
                        //
                        // We should probably have a method report.SetBuildStatus(error)
                        report.AddMessage(LogType.Error, errorMessageBuilder.ToString());
                    }
                    Console.WriteLine(p.GetAllOutput());
                }
            }
        }

<hr/>

    [MethodImpl(MethodImplOptions.InternalCall)]
    internal extern void AddMessage(LogType messageType, string message, string exceptionType);

**Comment by satchell78** [comment]
Try unticking and re-ticking the Android NDK Installed with Unity (recommended) under Editor Preferences and retry. - Lee_Hammerton

https://forum.unity.com/threads/burst-failes-to-compile-for-android.660394/

**Comment by Chrisx84** [comment]
it has nothing to do with android. i don't even have the NDK installed and i got the error. there is something seriously wrong with this new network system

**Comment by satchell78** [comment]
I agree there's something wrong at the moment. Your explanation was lacking and I figured I'd throw this in. Thanks for clarifying. I really hope there's a definite network solution by Unity 2019.3. Or better support for this until it's out of preview.

**Comment by timj-unity** [comment]
This is a burst issue and it looks like it has been fixed
