### ISSUE TITLE
NativeQueue<T>.Concurrent and .ToConcurrent() are deprecated

### ISSUE THREAD

**Issue by TomasRiker** [Unity-Technologies/multiplayer#47]
In the latest preview version of Unity.Collections, `NativeQueue<T>.Concurrent` and `NativeQueue<T>.ToConcurrent()` are marked as deprecated, which leads to compiler warnings.

**Comment by Armitage1982** [comment]
3 Days later they are now obsolete!
Things escalated quickly :-)

After fixing everything, documentation and projects ask for a « Ucg » namespace but Matchmaking or ServerQueryProtocol sources are nowhere to be found.

Given that networking is really a tough topic, I think I'm gonna search for any proven working solution cause I'm waaaay to lost with the « official » Networking solution (_or it is ?_).

**Comment by ptrefall** [comment]
Hopefully they will release a new version soon (hopefully before Unite at end of September).

**Comment by timj-unity** [comment]
New version is out now and it is using latest entities / collections
