### ISSUE TITLE
Error on spawn if asteroid count is zero: "IndexOutOfRangeException: Index 0 is out of range of '0' Length."

### ISSUE THREAD

**Issue by daschatten** [Unity-Technologies/multiplayer#49]
I experienced an issue spawning a player in my setup and could verify it with the asteroids sample. The same happens there if asteroid count is set to 0 and the player tries to spawn the ship.

`IndexOutOfRangeException: Index 0 is out of range of '0' Length.
Unity.Collections.NativeArray`1[T].FailOutOfRangeError (System.Int32 index) (at C:/buildslave/unity/build/Runtime/Export/NativeArray/NativeArray.cs:207)
Unity.Collections.NativeArray`1[T].CheckElementWriteAccess (System.Int32 index) (at C:/buildslave/unity/build/Runtime/Export/NativeArray/NativeArray.cs:126)
Unity.Collections.NativeArray`1[T].set_Item (System.Int32 index, T value) (at C:/buildslave/unity/build/Runtime/Export/NativeArray/NativeArray.cs:145)
GhostSendSystem`1+SerializeJob[TGhostSerializerCollection].Execute () (at Assets/NetCode/Snapshot/GhostSendSystem.cs:449)
Unity.Jobs.IJobExtensions+JobStruct`1[T].Execute (T& data, System.IntPtr additionalPtr, System.IntPtr bufferRangePatchData, Unity.Jobs.LowLevel.Unsafe.JobRanges& ranges, System.Int32 jobIndex) (at C:/buildslave/unity/build/Runtime/Jobs/Managed/IJob.cs:30)`

**Comment by daschatten** [comment]
Seems to be fixed if SpawnGhostJob is moved after SerializeJob.

**Comment by timj-unity** [comment]
This was fixed in the push last week
