### ISSUE TITLE
SocketException when Build Settings platform is iOS

### ISSUE THREAD

**Issue by Skjalgsm** [Unity-Technologies/multiplayer#5]
Hi,

I frequently have my editor set to iOS platform so that a lot of stuff that uses the UNITY_IOS define becomes active and I can test those things. But the multiplayer stuff now only returns a "SocketException: An address incompatible with the requested protocol was used." Switching back to PC/Mac & Linux Standalone platform solves the issue.

Would it be feasable to have the system figure out that even though the platform is set to iOS while in the editor that it should still use the Editor DLL like it normally does?

**Comment by timj-unity** [comment]
This has been fixed by adding a special case for UNITY_IOS && UNITY_EDITOR
