### ISSUE TITLE
2019.3.0a12 error in Asteroids sample after updating to latest entity/jobs/burst packages.

### ISSUE THREAD

**Issue by ptrefall** [Unity-Technologies/multiplayer#50]
`AtomicSafetyNode has either been corrupted or is being accessed on a job which is not allowed.
Unity.Collections.LowLevel.Unsafe.AtomicSafetyHandle:SetAllowSecondaryVersionWriting_Injected(AtomicSafetyHandle&, Boolean)
Unity.Collections.LowLevel.Unsafe.AtomicSafetyHandle:SetAllowSecondaryVersionWriting(AtomicSafetyHandle, Boolean)
Unity.Networking.Transport.DataStreamReader:.ctor(DataStreamWriter, Int32, Int32) (at F:/unity2019-projects/WorldOfLoot/com.unity.transport/Runtime/DataStream.cs:705)
Unity.Networking.Transport.GenericNetworkDriver`2:AppendPacket(NetworkEndPoint, UdpCHeader, Int32) (at F:/unity2019-projects/WorldOfLoot/com.unity.transport/Runtime/NetworkDriver.cs:1035)
Unity.Networking.Transport.ReceiveJob`1:Execute() (at F:/unity2019-projects/WorldOfLoot/com.unity.transport/Runtime/NetworkInterface.cs:185)`

**Comment by HoomanJCode** [comment]
same error on update. please release a new version if it is possible.

**Comment by iamtommo** [comment]
workaround is to dejobify and just poll on main thread

**Comment by HoomanJCode** [comment]
> workaround is to dejobify and just poll on main thread

that's so slow for servers!

**Comment by timj-unity** [comment]
This is fixed in the new package we pushed this week
