### ISSUE TITLE
iOS Runtime Error in Unity 2019.2.1f1 Build

### ISSUE THREAD

**Issue by kromenak** [Unity-Technologies/multiplayer#51]
I am using the latest Transport package code with Unity 2019.2.1f1. I've tested in Unity Editor, macOS Standalone, and Android - all three are working.

However, when I run on iOS, I see an error at startup:
`Unable to find internal function "Unity.Networking.Transport.NativeBindings::network_sendmsg"
Unity.Jobs.JobStruct1:Initialize()
Unity.Jobs.IJobExtensions:Schedule(T, JobHandle)
Unity.Networking.Transport.GenericNetworkDriver2:.cctor()`

If I later try to send data, the app crashes.

I was able to resolve similar-looking errors with ECS by adding entries to link.xml, but adding "Unity.Networking.Transport" to link.xml doesn't seem to help.

I had thought this was maybe an IL2CPP code stripping issue, but the package does work in Android and macOS builds built with IL2CPP enabled.

It would be great to fix this, but I'm also curious what the cause is (stripped code? incompatible Unity version? etc) and whether there's any workaround.

Thanks!

**Comment by kromenak** [comment]
I seem to have found a workaround for this issue. For some reason that I don't quite understand, the Job System doesn't seem to be able to find "NativeBindings.network_sendmsg" though it is a valid function and calling it outside the job system seems to work fine.

To work around this issue, I simply made the NetworkDriver not use the Job system during its update. I checked the code in GenericNetworkDriver.ScheduleUpdate to this:

`public JobHandle ScheduleUpdate(JobHandle dep = default(JobHandle))
{
            m_updateTime = Stopwatch.GetTimestamp() / TimeSpan.TicksPerMillisecond;

            // "ClearEventQueue" job.
            m_EventQueue.Clear();
            m_DataStream.Clear();

            // "UpdateJob" job.
            InternalUpdate();

            JobHandle handle = default(JobHandle);
            m_NetworkInterface.ScheduleReceive(this, handle).Complete();

            // "LogJob" job.
            m_Logger.FlushPending();
            m_Logger.Clear();
            return handle;
}`

So, instead of scheduling jobs to do this work, I just call the functions that the jobs would have called anyway. This is probably slower than using the job system would be, so maybe I'll wrap this code in UNITY_IOS defines so other platforms can still use the jobs system.

As I said, I really have no clue why the Jobs system approach isn't working on iOS! Maybe a bug in the Jobs package? If anyone's got any insight, I'd be interested!

**Comment by k-yanase** [comment]
I was also in trouble for the issue.
I Remove all [BurstCompile] attribute in multiplayer package, so the problem goes away in iOS.
I believe that BurstCompiler is the cause of that.

**Comment by kromenak** [comment]
Since com.unity.transport was converted to a 1st-class Unity Package, it's a little bit harder to actually modify the contents of the package as described above.

I found another thing that works here is...simply disable Burst compilation entirely! In 2019.3 (perhaps earlier versions too), you can go to "Project Settings > Burst AOT Settings > iOS" and select "Disable Burst Compilation".

**Comment by asyasmi** [comment]
Hi @kromenak and @k-yanase 

Sorry for such a long response from us.  My name is Anastasia, I’m a software developer in test engineer in Networking team. As a part of the old issues review and closure procedure, I’ve looked through this issue. Great you've solved it by yourself, and I'll add to our roadmap that we need to give proper documentation of specific details about building for mobile. 

Closing this issue, but in case of any additional questions/issues - please file a bug using Unity Bug reporter.
Thanks, Anastasia
