### ISSUE TITLE
Instructions to build Asteroids for client and server

### ISSUE THREAD

**Issue by wg-mblazin** [Unity-Technologies/multiplayer#54]
Can you please provide instructions for how to build standalone client and server? And also how to test both of them in the Play mode. Also the directives of UNITY_CLIENT and UNITY_SERVER are not really documented in Unity manual, can you please clarify if we have to set those manually or are they set automatically by the IDE?

At the moment I can only run if I set PlayMode to Server and build the client using UNITY_CLIENT directive manually set. If I try to set UNITY_SERVER directive the compilation fails. I have to run the server in PlayMode Server settings so I can get 2 clients connected.

Just a README.md would be great.

**Comment by timj-unity** [comment]
Added a section on building standalone and the defines in the docs
https://docs.unity3d.com/Packages/com.unity.netcode@0.0/manual/client-server-worlds.html#standalone-builds

**Comment by falk-stefan** [comment]
First off: Thanks for this project. I couldn't find a simple multiplayer projects (except for the FPS shooter) which uses DOTS. Asteroids is much more digestable imo.

Regarding #54: I had the same question. As @wg-mblazin suggested, maybe add a hint and the link in the README.md of the github project?
