### ISSUE TITLE
Error during installation of com.unity.transport

### ISSUE THREAD

**Issue by thesourceoferror** [Unity-Technologies/multiplayer#55]
During startup of my unity project, I receive the following message:

> An error occurred while resolving packages:
Project has invalid dependencies:
com.unity.transport
[C:\Users\me\Desktop\UnityProjects\Prototype Projects\Packages\multiplayer\com.unity.transport\package.json] cannot be found
A re-import of the project may be required to fix the issue or a manual modification of C:\Users\me\Desktop\UnityProjects\Prototype Projects\Packages\manifest.json file.

Now, I have installed the multiplayer folder from: https://github.com/Unity-Technologies/multiplayer. The "multiplayer" folder was placed two folders up from the project that I wish to use it in. I followed the direction provided in the documentations folder and I am confused about what I have done wrong.

Any help would be much appreciated, thanks!

**Comment by timj-unity** [comment]
The transport is now available as a proper unity package, which should fix all path-related issues like this
