### ISSUE TITLE
Obtain remote IP address

### ISSUE THREAD

**Issue by bryanfiles** [Unity-Technologies/multiplayer#56]
I've searched the code in com.unity.transport but can't find a way to obtain the IP address of accepted connections.  I see I can get a NetworkEndPoint from the driver, but anything I might use there to get the IP address is internal.  Am I missing something?

**Comment by derekdominoes** [comment]
NetworkDriver.RemoteEndPoint( NetworkConnection conn ) returns a NetworkEndPoint. Its rawNetworkAddress.ipv4 bits can be swizzled to the the address. I do this on when I Accept a connection. Seems to work fine.

**Comment by asyasmi** [comment]
Hi 

Sorry for such a long response from us.  My name is Anastasia, I’m a software developer in test engineer in Networking team. As a part of the old issues review and closure procedure, I’ve looked through this issue. 

`NetworkDriver.RemoteEndPoint(NetworkConnection con).Address` returns string `IP:port` of obtained connection. 
`NetworkDriver.RemoteEndPoint(NetworkConnection con).rawNetworkAddress.ipv4` or `NetworkDriver.RemoteEndPoint(NetworkConnection con).rawNetworkAddress.ipv6` will provide uint from which you can concat IP address and port also. 

Closing this issue, but in case of any additional questions/issues - please file a bug using Unity Bug reporter.
Thanks, Anastasia
