### ISSUE TITLE
Update package.json

### ISSUE THREAD

**Issue by Guedez** [Unity-Technologies/multiplayer#57]
After following the instructions to install, because I had already quite a bit of other packages installed, a lot of conflicts arose.
I fixed it by changing the com.unity.transport dependencies in the package.json to whatever version of those I am currently using and it worked. but I can see this being a roadblock to some people, also, give it a proper displayName, I am currently using Transport

**Comment by timj-unity** [comment]
It's been moved to a proper package and the dependencies have been updated. New display name is "Unity Transport"

**Comment by churbis** [comment]
Tim this does not appear to be showing up in the Package Manager using
2019.3

**Comment by timj-unity** [comment]
I'll investigate, in the meantime you can add the package to manifest.json manually, see https://github.com/Unity-Technologies/multiplayer/blob/master/sampleproject/Packages/manifest.json for an example
