### ISSUE TITLE
The jobfied example does not work at all

### ISSUE THREAD

**Issue by Guedez** [Unity-Technologies/multiplayer#58]
It not only does not compile because of the lack of the pipeline parameter
If you set it to default, the result is a ton of job errors related to writing when shouldn't and whatnot

**Comment by WAYNGROUP** [comment]
Hi,

I managed to make it work here : 
https://github.com/WAYNGROUP/Unity-Networking-Experiments

I also managed to use a custom struct instead of a primitive type.

**Comment by timj-unity** [comment]
Tried the jobified sample in the latest version, seems to work fine now
