### ISSUE TITLE
Same code connects on PC, but doesn't on android

### ISSUE THREAD

**Issue by Zolden** [Unity-Technologies/multiplayer#59]
What should I do if I want to find a reason why doesn't my networking code work on android as it does if built to PC?

In particular, when I'm trying to connect android client with PC server, server gets and reacts to connect request, but client doesn't get the connection accepted message back.

While the same client build for PC and runned on another pc (in the same network as the android device) works as intended. What could be the problem here, I can't even start debugging, because I don't understand, what could be wrong.

Can anyone share any idea about what direction should I start moving in attempt to understand what's wrong here?

(I'm using the latest version of com.unity.multiplayer-hlapi)

**Comment by timj-unity** [comment]
This repo is completely separate from multiplayer-hlapi. multiplayer-hlapi is UNet, the forum for that might be a good place to start, https://forum.unity.com/forums/connected-games.26/
