### ISSUE TITLE
ClientServerSubScene doesn't work

### ISSUE THREAD

**Issue by Jawsarn** [Unity-Technologies/multiplayer#61]
Doesn't produce any entities when used with SubScene.
Tested with Unity 2019.2.7f2 and Entities 0.1.1
It seems that SubScene destroys all previous entities created with same script before checking to create new, so none are created in total when used together.

**Comment by timj-unity** [comment]
ClientServerSubScene has been removed, in new entities sub scenes are loaded in all worlds so it is not needed. It is also possible to use the new NetCodeConversionSettings to convert subscenes differently depending on target. We will add more samples on how to do that.

**Comment by Jawsarn** [comment]
I don't see this as a good thing. You don't typically have the client and server in the same executable in the end, and to simulate this you should be able to explicitly tell what world the subscene belongs to in some way? And in my case I have more worlds in my project that are not client or server, but login and matchmaking.
