### ISSUE TITLE
Where is the server query protocol sample code?

### ISSUE THREAD

**Issue by andykais** [Unity-Technologies/multiplayer#62]
The readme states:
> The code required to support the Server Query Protocol is available in samplesproject/Assets/ServerQueryProtocol/ 

but this documentation is out of date. Where is the server query protocol code and how do I add it to unity? I want to use the sample project to test getting information over the server query protocol but I do not know how to start it. Apologies for obvious questions here but also thank you in advance.

**Comment by tvrDev** [comment]
it is a package now.
```
  "dependencies": {
	"com.unity.ucg.usqp": "0.1.0-preview",
        ...
   }
```

**Comment by andykais** [comment]
Thank you. My goal is to actually write a client to hit the server query protocol udp endpoint. We are working to write an intelligent game server scaling tool which needs to know the number of players active on a dedicated server. I have gotten the `Samples/Ping-Multiplay` example scene running (which is the sample which shows UsqpServer usage) but I was actually hoping I could hit the server query protocol. Is there any documentation on hitting its endpoint from an external service? I have started peaking into the `Unity.Ucg.Usqp.UsqpServer` code to try and reverse engineer a query to it, but it would be fantastic if I had a short code snippet showing how to pull player count data out of it.

I guess an important question as well is if this is even possible to do with an external client. I see code for things like generating tokens in the server code (`UsqpServer.GetNextToken`). Also If this is not the place for these questions please redirect me!

**Comment by GirtheGameDesigner** [comment]
https://bintray.com/package/files/unity/unity-staging/com.unity.xr.openvr?order=desc&sort=fileLastModified&basePath=.npm%2Fcom.unity.ucg.usqp&tab=files

**Comment by timj-unity** [comment]
The SQP is no longer part of this repo. It is being moved to a package by another team in unity. Please ask in https://forum.unity.com/forums/connected-games.26/ to get more information about the current status of it
