### ISSUE TITLE
ReliableSequencedPipelineStage memory leak

### ISSUE THREAD

**Issue by KentaYanase** [Unity-Technologies/multiplayer#63]
ReliableSequencedPipelineStage.Send method is leak,

needUpdate = true   -> Memory Leak
needUpdate = false  -> Not Memory Leak

but, if needUpdate is false, it ssem not to work Reliable UDP. I can't fix the Pipeline ...

**Comment by asyasmi** [comment]
Hi @KentaYanase 

Sorry for such a long response from us.  My name is Anastasia, I’m a software developer in test engineer in Networking team. As a part of the old issues review and closure procedure, I’ve looked through this issue. 

In latest package version in [ReliableSequencedPipelineStage](https://docs.unity3d.com/Packages/com.unity.transport@0.3/api/Unity.Networking.Transport.ReliableSequencedPipelineStage.html) Send method does not contain needsUpdate anymore. 


Closing this issue, but in case you still able to reproduce this problem or any additional questions/issues - please file a bug using Unity Bug reporter.
Thanks, Anastasia
