### ISSUE TITLE
Connecting to wrong port cause errors.

### ISSUE THREAD

**Issue by Jawsarn** [Unity-Technologies/multiplayer#64]
Simply, conencting to wrong port etc cause "InvalidOperationException: Cannot send data while connecting" from CommandSendSystem. This strangely also adds another error each frame of "InvalidOperationException: The parallel network driver needs to process a single unique connection per job, processing a single connection multiple times in a parallel for is not supported.". 

This is always a problem even if you connect to the correct port if you connect within the client simulation and not after CommandSendSystem.

This is sometimes a problem if you connect to the correct port and you have a bad framerate where you get another client sim tick before server tick.

To replicate simply change the port for client connect in asteroids demo.

**Comment by timj-unity** [comment]
This has been fixed in the updated version. The CommandSendSystem no longer runs until you are fully connected and in-game
