### ISSUE TITLE
Samples don't work on Linux

### ISSUE THREAD

**Issue by alfiare** [Unity-Technologies/multiplayer#65]
If you simply download and attempt to run the samples on Linux (after you get around the Burst package dependency problem with Mathematics) you will only get an error when running:

DllNotFoundException: network.bindings
Unity.Networking.Transport.IPv4UDPSocket.Initialize () (at /home/master/Projects/multiplayer-master/com.unity.transport/Runtime/NetworkInterface.cs:145)
Unity.Networking.Transport.GenericNetworkDriver`2[T,TNetworkPipelineStageCollection]..ctor (Unity.Networking.Transport.INetworkParameter[] param) (at /home/master/Projects/multiplayer-master/com.unity.transport/Runtime/NetworkDriver.cs:355)
Unity.Networking.Transport.UdpNetworkDriver..ctor (Unity.Networking.Transport.INetworkParameter[] param) (at /home/master/Projects/multiplayer-master/com.unity.transport/Runtime/NetworkDriver.cs:1194)
NetworkStreamReceiveSystem.OnCreateManager () (at Assets/NetCode/Connection/NetworkStreamReceiveSystem.cs:89)
Unity.Entities.ComponentSystemBase.CreateInstance (Unity.Entities.World world) (at Library/PackageCache/com.unity.entities@0.0.12-preview.33/Unity.Entities/ComponentSystem.cs:201)
Unity.Entities.World.AddSystem[T] (T system) (at Library/PackageCache/com.unity.entities@0.0.12-preview.33/Unity.Entities/World.cs:341)
Unity.Entities.World.CreateSystemInternal (System.Type type, System.Object[] constructorArguments) (at Library/PackageCache/com.unity.entities@0.0.12-preview.33/Unity.Entities/World.cs:235)
Unity.Entities.World.GetOrCreateSystemInternal (System.Type type) (at Library/PackageCache/com.unity.entities@0.0.12-preview.33/Unity.Entities/World.cs:251)
Unity.Entities.World.GetOrCreateSystem[T] () (at Library/PackageCache/com.unity.entities@0.0.12-preview.33/Unity.Entities/World.cs:272)
GhostSendSystem`1[TGhostSerializerCollection].OnCreateManager () (at Assets/NetCode/Snapshot/GhostSendSystem.cs:121)
Unity.Entities.ComponentSystemBase.CreateInstance (Unity.Entities.World world) (at Library/PackageCache/com.unity.entities@0.0.12-preview.33/Unity.Entities/ComponentSystem.cs:201)
Unity.Entities.World.AddSystem[T] (T system) (at Library/PackageCache/com.unity.entities@0.0.12-preview.33/Unity.Entities/World.cs:341)
Unity.Entities.World.CreateSystemInternal (System.Type type, System.Object[] constructorArguments) (at Library/PackageCache/com.unity.entities@0.0.12-preview.33/Unity.Entities/World.cs:235)
Unity.Entities.World.GetOrCreateSystemInternal (System.Type type) (at Library/PackageCache/com.unity.entities@0.0.12-preview.33/Unity.Entities/World.cs:251)
Unity.Entities.World.GetOrCreateSystem (System.Type type) (at Library/PackageCache/com.unity.entities@0.0.12-preview.33/Unity.Entities/World.cs:279)
ClientServerBootstrap.Initialize (System.Collections.Generic.List`1[T] systems) (at Assets/NetCode/ClientServerWorld.cs:495)
Unity.Entities.DefaultWorldInitialization.GetAllSystems (Unity.Entities.WorldSystemFilterFlags filterFlags) (at Library/PackageCache/com.unity.entities@0.0.12-preview.33/Unity.Entities.Hybrid/Injection/DefaultWorldInitialization.cs:253)
Unity.Entities.DefaultWorldInitialization.Initialize (System.String worldName, System.Boolean editorWorld) (at Library/PackageCache/com.unity.entities@0.0.12-preview.33/Unity.Entities.Hybrid/Injection/DefaultWorldInitialization.cs:53)
Unity.Entities.AutomaticWorldBootstrap.Initialize () (at Library/PackageCache/com.unity.entities@0.0.12-preview.33/Unity.Entities.Hybrid/Injection/AutomaticWorldBootstrap.cs:11)

**Comment by timj-unity** [comment]
Duplicate of issue #36
