### ISSUE TITLE
ClientServerSubScene doesn't work

### ISSUE THREAD

**Issue by spectre1989** [Unity-Technologies/multiplayer#66]
If you call UpdateSceneEntities multiple times it will destroy the entities in the entity manager of the previous call, so this script doesn't do what it's intended to do.

**Comment by timj-unity** [comment]
ClientServerSubScene no longer exists. Newer entities load scenes on all worlds and you can use NetCodeConversionSettings to control how subscene is converted

**Comment by spectre1989** [comment]
Cheers Tim
