### ISSUE TITLE
Is this repository still active?

### ISSUE THREAD

**Issue by cyraid** [Unity-Technologies/multiplayer#67]
With the last change that happened 4 months ago, is this repository still active? I'm starting a project with NetCode, but need to know if NetCode will be supported and worked on.

Edit: I did read on this [Unity Forum Post](https://forum.unity.com/threads/dots-multiplayer-discussion.694669/) that this repository isn't the main one. Would we have to wait for a public repository / package?

**Comment by ptrefall** [comment]
The next Netcode package comes with the Netcode TPS sample they showed at Unite. Its about to drop any week now. Ante said ~1 month mid October. But how close they're able to land all depends on the estimation gods.

**Comment by Skjalgsm** [comment]
The repository isn’t a traditional open source one. It’s just a snapshot of
what it looks like internally whenever they bother to update it. As far as
i know they don’t accept PR’s or even monitor these comments much.

**Comment by johnroodt** [comment]
Thanks
John Roodt
Cell: +61 402 099 974

**Comment by timj-unity** [comment]
This repo is the public version of all samples, but it is not the main development repo. The samples here are updated when we make new released of the netcode and transport packages.

**Comment by spectre1989** [comment]
Any update on when we might expect the next drop?

**Comment by spectre1989** [comment]
Ooh, looks like it just landed
