### ISSUE TITLE
Crush when i open any scene.

### ISSUE THREAD

**Issue by igavva** [Unity-Technologies/multiplayer#68]
Crush unity when i open any scene.

Unity 2019.3.0b11 Netcode 0.0.2

I create new scene and copy Asteroids. Editor work fine. But when i build windows platform: 

`Library\PackageCache\com.unity.netcode@0.0.2-preview.1\Runtime\Connection\NetworkStreamReceiveSystem.cs(39,21): error CS0649: Field 'NetworkStreamReceiveSystem.m_ClientPacketDrop' is never assigned to, and will always have its default value 0`

`Library\PackageCache\com.unity.netcode@0.0.2-preview.1\Runtime\Connection\NetworkStreamReceiveSystem.cs(38,21): error CS0649: Field 'NetworkStreamReceiveSystem.m_ClientPacketDelay' is never assigned to, and will always have its default value 0`

I delete m_ClientPacketDelay and m_ClientPacketDrop from NetworkStreamReceiveSystem.cs. Windows build is worked.

**Comment by timj-unity** [comment]
Thank you for reporting, the issue has been fixed and the fix will be in the next release of the netcode package
