### ISSUE TITLE
Any way to broadcast a message using UdpNetworkDriver?

### ISSUE THREAD

**Issue by EliBukchin** [Unity-Technologies/multiplayer#69]
I am trying to write LAN server discovery code to use for creating a mobile "controller" app
for a Desktop unity project.

**Comment by asyasmi** [comment]
Hi @EliBukchin, 

Sorry for such a long response from us.  My name is Anastasia, I’m a software developer in test engineer in Networking team. As a part of the old issues review and closure procedure, I’ve looked through this issue. 

We don't have broadcast implemented yet, although it's on a backlog and planned for upcoming versions. 

Closing this issue, but in case of any additional questions/issues - please file a bug using Unity Bug reporter.
Thanks, Anastasia
