### ISSUE TITLE
ArgumentException: An item with the same key has already been added. Key: UnityEditor.Experimental.TerrainAPI.PaintHeightTool

### ISSUE THREAD

**Issue by gra-am** [Unity-Technologies/multiplayer#70]
Trying to use the new terrain tools (version 2.0.2) in this project and running into this issue. 

I assume that it will be fixed in the future as terrain is outside the scope of the current feature set of NetCode.

```
ArgumentException: An item with the same key has already been added. Key: UnityEditor.Experimental.TerrainAPI.PaintHeightTool
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <437ba245d8404784b9fbab9b439ac908>:0)
Unity.NetCode.Editor.GhostAuthoringComponentEditor.GenerateGhost (Unity.NetCode.GhostAuthoringComponent ghostInfo) (at Library/PackageCache/com.unity.netcode@0.0.4-preview.0/Editor/GhostAuthoringComponentEditor.cs:443)
Unity.NetCode.Editor.GhostAuthoringComponentEditor.OnInspectorGUI () (at Library/PackageCache/com.unity.netcode@0.0.4-preview.0/Editor/GhostAuthoringComponentEditor.cs:272)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass55_0.<CreateIMGUIInspectorFromEditor>b__0 () (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/InspectorElement.cs:521)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at /Users/builduser/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:187)
```

**Comment by malcartwright** [comment]
I have the same problem. To get passed this, I modify the code in the GhostAuthoringComponentEditor.GenerateGhost method at line 442 to:
`if (compType.Type != null && !typeLookup.ContainsKey(compType.Type.FullName))`

This avoids the attempt to add the same type to the dictionary more than once.

**Comment by asyasmi** [comment]
Hi 

Sorry for such a long response from us.  My name is Anastasia, I’m a software developer in test engineer in Networking team. As a part of the old issues review and closure procedure, I’ve looked through this issue. 

We are rebuilding GhostGeneration now. I've reported this as a bug in FogBugz (http://fogbugz.unity3d.com/default.asp?1259823_f7c1v7uaddjtljtk), and will recheck once we will be done with new code generation. 

Closing this issue, but in case of any additional questions/issues - please file a bug using Unity Bug reporter.
Thanks, Anastasia
