### ISSUE TITLE
Unity Editor crashes immediately when pressing 'Update Component List' on the Ghost Authoring Component (0.0.4). 

### ISSUE THREAD

**Issue by gra-am** [Unity-Technologies/multiplayer#71]
This [tutorial](https://docs.unity3d.com/Packages/com.unity.netcode@0.0/manual/getting-started.html) states: 

> Then, in the Inspector, add the Ghost Authoring Component to the Prefab. In this component, select Update Component List to update the list of components.

However, pressing this button crashes the editor immediately, with no errors. I have replicated this on two separate Macs. 

Pressing the 'Generate code' button beforehand seems to resolve the issue. It would be helpful if the tutorial reflected this.

**Comment by Dmajster** [comment]
Suffering from the same issue. Running Windows 10 Pro build 18362. Generating Code does not fix the issue for me.

**Comment by swirllyman** [comment]
> Suffering from the same issue. Running Windows 10 Pro build 18362. Generating Code does not fix the issue for me.
> 
> [edit] Resolved the issue by adding a / to my Root Path in my Ghost Authoring Component and then generating the code before updating the component list. [/edit]

This fixed it for me. Make sure you set that path!

**Comment by asyasmi** [comment]
Hi @gra-am, @Dmajste and @swirllyman, 

Sorry for such a long response from us.  My name is Anastasia, I’m a software developer in test engineer in Networking team. As a part of the old issues review and closure procedure, I’ve looked through this issue. 

This had been fixed ages ago and checked on 
```
netcode: 0.2.0-preview.5
transport: 0.3.1-preview.4
```

 so I'm closing this issue, but in case of any additional questions/issues - please file a bug using Unity Bug reporter.
Thanks, Anastasia
