### ISSUE TITLE
ICustomBootstrap priority

### ISSUE THREAD

**Issue by Jawsarn** [Unity-Technologies/multiplayer#72]
Please add so you can specify priority instead or as well to the hierarchical rule that currently exists.

To add more worlds I have currently made a custom bootstrap (extended the supplied one) and with editorscript which clones the netcode, modifies, and adds additional simulation groups for new worlds. ( I had to copy and modify to be able to modify the ClientSimulationSystemGroup or NetworkStreamReceiveSystem to add additional netcode in the client world - so I decided to copy everything and put it under my own namespace)

I want to keep the netcode in my project to be able to check for updates and simply use my script to redo my generation of worlds, but the ICustomBootstrap crashes since it has two of them that are not in hierarchy.

I would ask to add either some encapsulation of a define, or another attribute to add that can have a priority.

**Comment by asyasmi** [comment]
Hi @Jawsarn, 

Sorry for such a long response from us.  My name is Anastasia, I’m a software developer in test engineer in Networking team. As a part of the old issues review and closure procedure, I’ve looked through this issue. 

I've talked a bit with guys about your issue and I think the best options are: 
1. If you have ICustomBootstrap crashing, it'd be great if you report this as a bug so Entities team can take a look on it and 
2. If you still facing this issue and simple solutions like overriding default NetCode are not working for you, it worth moving your question to [Dots forum](https://forum.unity.com/threads/dots-multiplayer-discussion.694669/page-3) where we can keep this discussion more up-to-date. 

Closing this issue, but in case of any additional questions/issues - please file a bug using Unity Bug reporter.
Thanks, Anastasia
