### ISSUE TITLE
package not found

### ISSUE THREAD

**Issue by freaksdd** [Unity-Technologies/multiplayer#73]
In the Install-description are written you have to open the Editor from the Version 2019.1.0f1 or later and then you can find the Package in the Package Manager under 'Unity Transport' include the preview option. I had look in the Version 2019.1.0f2 and 2019.3.0b4 of the package-manger and can't find the Package.
Is it possible to edit the JSON File to include the Unity Transport or is it renamed?

**Comment by benjamminlaner** [comment]
I'm also having this issue, wondering if it's some sort of assembly issue?

**Comment by lukemadera** [comment]
I am having the same issue with Transport and NetCode (neither show up, even with Preview turned on). I do see DOTS and Entities. I'm on Unity 2019.2. How do I add transport?

**Comment by souleater007** [comment]
I am also having the same issue.

**Comment by Roesh** [comment]
Running into this as well. I'm starting a new project and would prefer to get started with the latest tools as opposed to using Unet which is being deprecated

**Comment by asyasmi** [comment]
Hi 

Sorry for such a long response from us.  My name is Anastasia, I’m a software developer in test engineer in Networking team. As a part of the old issues review and closure procedure, I’ve looked through this issue. 

I've transferred this issue to Package manager team. I've checked using Version 2019.3.15f1 (49593feec2a2) and it works fine. 
But in case, you can manually add dependencies to `manifest.json`: 
```
   ...
   "com.unity.netcode": "0.2.0-preview.5",
   "com.unity.transport": "0.3.1-preview.4",
   ...
```
and they will appear in Package Manager also. 

Closing this issue, but in case of any additional questions/issues - please file a bug using Unity Bug reporter.
Thanks, Anastasia
