### ISSUE TITLE
Ghost Collection Authoring Component invalid name prefix

### ISSUE THREAD

**Issue by island212** [Unity-Technologies/multiplayer#74]
I found a small bug in Ghost Collection Authoring Component. It use the project name as a name prefix for the code generation and my project name was "Getting started with NetCode". So yeah the code has space in the class signature and couldn't compile.

I solved it by simply changing the name prefix for "GettingStartedWithNetCode". Like I say, nothing too big but I thought I should mention it.

Maybe a warning, an error or change the space for a _ in generated code.

**Comment by asyasmi** [comment]
Hi @island212, 

Sorry for such a long response from us.  My name is Anastasia, I’m a software developer in test engineer in Networking team. As a part of the old issues review and closure procedure, I’ve looked through this issue. 


This had been fixed and you can check it up in: 
```
netcode: 0.2.0-preview.5
transport: 0.3.1-preview.4
```

Closing this issue, but in case of any additional questions/issues - please file a bug using Unity Bug reporter.
Thanks, Anastasia
