### ISSUE TITLE
DisableAutoCreation Standalone Error

### ISSUE THREAD

**Issue by AffaxDev** [Unity-Technologies/multiplayer#75]
I followed the NetCode tutorial step-by-step. 
When I build a standalone build, the NetCode systems don't get started because of [DisableAutoCreation].

[Error log](https://hastebin.com/qazojemaja.sql)
(sorry if the issue submission is bad, it's my first time)

**Comment by asyasmi** [comment]
Hi @AffaxDev, 

Sorry for such a long response from us.  My name is Anastasia, I’m a software developer in test engineer in Networking team. As a part of the old issues review and closure procedure, I’ve looked through this issue. 

It'd be cool if you were able to send us the project using Bug Reporter, if you're still facing this issue. I've tried to reproduce but was unable to reproduce it. 

Closing this issue, but in case of any additional questions/issues - please file a bug using Unity Bug reporter.
Thanks, Anastasia
