### ISSUE TITLE
Add way to get ping to client

### ISSUE THREAD

**Issue by qhdwight** [Unity-Technologies/multiplayer#76]
For my game, it needs the RTT to a client in order to roll back the hitboxes properly. I noticed this feature is missing or not obvious to get. It is common in many other networking libraries, like in the old UNET transport and also Lidgren.

**Comment by asyasmi** [comment]
Hey @qhdwight, 
Sorry for such a long response from us.  My name is Anastasia, I’m a software developer in test engineer in Networking team. As a part of the old issues review and closure procedure, I’ve looked through this issue. 

Probably, it'd be worth looking at `ReliableUtility.RTTInfo` [here](https://docs.unity3d.com/Packages/com.unity.transport@0.3/api/Unity.Networking.Transport.Utilities.ReliableUtility.RTTInfo.html). Please update us if that works for you. 

Closing this issue, but in case of any additional questions/issues - please file a bug using Unity Bug reporter.
Thanks, Anastasia
