### ISSUE TITLE
Not able to import the Unity Transport package

### ISSUE THREAD

**Issue by mehervihari** [Unity-Technologies/multiplayer#77]
As per the installation guide, I tried to import the Transport package but it gave a dependency issue saying "unable to add package.........invalid dependencies: com.unity.collections package cannot be found".
So, I tried to install the collections package but again it gave a dependency issue saying "unable to add package.........one or more dependencies cannot be added :com.unity.testframework 1.3.0 package cannot be found".
But I couldn't find this testframework 1.3.0 package anywhere in unity and hence I couldn't use the transport package for networking.

**Comment by sivatejachigicherla** [comment]
This happens due to the internal network proxy.Contact your administrator for help.

**Comment by asyasmi** [comment]
Hi @mehervihari 

Sorry for such a long response from us.  My name is Anastasia, I’m a software developer in test engineer in Networking team. As a part of the old issues review and closure procedure, I’ve looked through this issue. 

I'd suggest checking your Unity version and installing appropriate TestFramework package version using Package Manager. 

Closing this issue, but in case of any additional questions/issues - please file a bug using Unity Bug reporter.
Thanks, Anastasia
