### ISSUE TITLE
NetCube choppy on Android

### ISSUE THREAD

**Issue by tinnystudios** [Unity-Technologies/multiplayer#78]
Hey guys, running the NetCube example on android seems to be choppy once every few seconds.

**Comment by asyasmi** [comment]
Hi @tinnystudios 

Sorry for such a long response from us.  My name is Anastasia, I’m a software developer in test engineer in Networking team. As a part of the old issues review and closure procedure, I’ve looked through this issue. 

I've tried to reproduce this issue but did not really succeed, thus NetCube is not working for Android now. Closing this issue, but in case of any additional questions/issues or you're still facing it, it'd be great if you file it trough Bug Reporter. 

Thanks, Anastasia
