### ISSUE TITLE
Crash in Windows StandAlone x86

### ISSUE THREAD

**Issue by areilly711** [Unity-Technologies/multiplayer#79]
Using the ServerBehaviour and ClientBehaviour from the Transport docs, it works in the editor, but when I make an x86 build it automatically crashes. Making a x64 build does work
2019.3.1f1
Transport 0.2.3

**Comment by asyasmi** [comment]
Hi @areilly711,  

Sorry for such a long response from us.  My name is Anastasia, I’m a software developer in test engineer in Networking team. As a part of the old issues review and closure procedure, I’ve looked through this issue. 

I've moved your issue to our FogBugz and you can follow it by link: 
http://fogbugz.unity3d.com/default.asp?1259987_p1ni691cncmb43o8


Closing this issue, but in case of any additional questions/issues - please file a bug using Unity Bug reporter.
Thanks, Anastasia
