### ISSUE TITLE
non-existent assembly 'Unity.Collections'

### ISSUE THREAD

**Issue by shovancj** [Unity-Technologies/multiplayer#8]
Followed the guide line here. https://github.com/Unity-Technologies/multiplayer/blob/master/com.unity.transport/Documentation/install.md

got this error. Said to report errors if I have errors at that step. 

I'm using Unity 2018.3.0b3

**Comment by Skjalgsm** [comment]
Yeah, you also need com.unity.collections. They should update their guide

![image](https://user-images.githubusercontent.com/568589/48438284-ec8a0380-e783-11e8-9f24-442b4acb586b.png)

**Comment by shovancj** [comment]
Thanks for the quick reply. not sure how to add the com.unity.collections

do i just add it to the manifest.json?

**Comment by Skjalgsm** [comment]
You open the package manager and select show preview packages and then install the collections package
![image](https://user-images.githubusercontent.com/568589/48438515-70dc8680-e784-11e8-91ad-5d0a20245771.png)

**Comment by shovancj** [comment]
hrm.. so in offline mode.. ie this machine that im developing on cant be online. 

I have warnings on my packages window.

bottom left corner.. instead of updated with a data it says you seem to be offline.

I also have error boxes next to collections, mathmatics and transport.

![packageoffline](https://user-images.githubusercontent.com/45015293/48439106-838a9780-e753-11e8-971d-d2180fdb529d.png)

**Comment by shovancj** [comment]
I could press the + at the bottom to navigate locally on the machine to the package to include, but i do not have it and I'm failing to find it on the net.

**Comment by Skjalgsm** [comment]
Then you also need mathematics. If you cant use the package manager then you need to download the reposetories and copy them over yourself.
https://github.com/Unity-Technologies/Unity.Mathematics

**Comment by shovancj** [comment]
Thanks again SKjalgsm!

I was able to just install 2018.3.0b8 to my machine that i can get online with.. 

Then use the package manager via unity to download packages. and then take those packages and use the "+" button on the Package Manager window as you directed to get things happy.

thanks again so much for your help.

**Comment by Skjalgsm** [comment]
If you managed to find a solution to your problem, then please close this issue @shovancj

**Comment by shovancj** [comment]
Sorry meant to close it with the above. 

Had to download the packages via a computer that can reach online. while connected to unity. ie there is no place currently that I seen to download up to date packages without having a machine connected to the net with unity,
