### ISSUE TITLE
[Unity.Transport 0.3] Read a NativeArray<byte>

### ISSUE THREAD

**Issue by Pyrobeerbeer** [Unity-Technologies/multiplayer#81]
Hi,
Before Unity.Transport 0.3 when we have an array of bytes to send them i write with function "DataStreamWriter.Write(byteArray, LenghtOfArray); " i send them and i receive data i read them with "DataStreamReader.ReadBytesAsArray(ref readerContext, LenghtOfArray)" and they return me a byte array. With new update we can't write byte array directly but we can write an "NativeArray<byte>"
so no problem for write but when i send data, i receive them but  "DataStreamReader" they haven't function return read value like before. For example DataStreamReader.ReadBytes retun void . Can you help me please ? thanks !

**Comment by bibbis** [comment]
Hi,
I was confused by this too.

Try this:
NativeArray<byte> _data = new NativeArray<byte>(2, Allocator.Temp);
_stream.ReadBytes(_data);

I'm expecting to receive 2 bytes in my array. You probably need a different number.
The first byte tells me what type of message it is, and the second byte will mean something different depending on the type.

The documentation says "Read and copy data into the given NativeArray of bytes, an exception will be thrown if not enough bytes are available."
https://docs.unity3d.com/Packages/com.unity.transport@0.3/api/Unity.Networking.Transport.DataStreamReader.html#Unity_Networking_Transport_DataStreamReader_ReadBytes_NativeArray_System_Byte__

How come the "out" keyword is not used here?
