### ISSUE TITLE
System.InvalidOperationException: EndSend without matching BeginSend Error!

### ISSUE THREAD

**Issue by HoomanJCode** [Unity-Technologies/multiplayer#83]
I have started a dedicated server for my game and its crash with this error:

> System.InvalidOperationException: EndSend without matching BeginSend
Thrown from job: Network.Server.ServerNetworkSystem.SendHealthJob
This Exception was thrown from a job compiled with Burst, which has limited exception support. Turn off burst (Jobs -> Burst -> Enable Compilation) to inspect full exceptions & stacktraces. In this standalone build configuration burst will now abort the Application.
(Filename: C:\buildslave\unity\build\Runtime/Jobs/ScriptBindings/JobsBindings.cpp Line: 52)

then I checked my code at  Network.Server.ServerNetworkSystem.SendHealthJob. it is my send function:
```
            public static void SendHealth(ref NetworkDriver.Concurrent driver, NetworkConnection toPlayer,
                NetworkIdentity healthOfPlayer, float health, float maxHealth)
            {
                var writer = driver.BeginSend(toPlayer);
                //HealthIs command
                //command id
                writer.WriteByte(ClientNetworkSystem.Commands.HealthIs);
                //player id (hash code of connection)
                writer.WriteUInt(healthOfPlayer.Id);
                //health
                writer.WriteByte((byte) (health * 255 / maxHealth));
                driver.EndSend(writer);
            }
```
the job is IJobForEach and i have turned off burst compile.

**Comment by asyasmi** [comment]
Hi @HoomanJCode, 

Sorry for such a long response from us.  My name is Anastasia, I’m a software developer in test engineer in Networking team. As a part of the old issues review and closure procedure, I’ve looked through this issue. 

If you're still experiencing this issue with the latest changes of packages, it'd be cool if you can send part of your code or project using Bug Reporter, so we can take a look at it. From first sight, this part of the code looks fine and I cannot clearly see where the crash happens.

Closing this issue, but in case of any additional questions/issues - please file a bug using Unity Bug reporter.
Thanks, Anastasia
