### ISSUE TITLE
NetCode for singleplayer

### ISSUE THREAD

**Issue by SupinePandora43** [Unity-Technologies/multiplayer#87]
NetCode creates 2 worlds, Server and Client.
my scene has 100 cubes, then Server+Client entities = 200 cubes!!!
i don't know way to use only "Default World" for SinglePlayer
and "Server"+"Client" for MultiPlayer

any help?

**Comment by adammpolak** [comment]
@SupinePandora43 sorry, why would you need Netcode for single player?

**Comment by SupinePandora43** [comment]
@adammpolak i mean i would like to have only one world for situations when player whants play with bots, and two worlds when whant to rent a local server

**Comment by adammpolak** [comment]
@SupinePandora43 you will probably want to take a look at [this file](https://github.com/Unity-Technologies/multiplayer/blob/master/sampleproject/Assets/Samples/NetCodeBootstrap.cs)

This is where unity initializes world and systems.

You can find more information on how bootstrap works [here](https://docs.unity3d.com/Packages/com.unity.netcode@0.1/manual/client-server-worlds.html#bootstrap)

It seems like you would like a player to choose "single player" or "multi-player". You would have to decide where to make the split. Sounds like you might want to make them as 2 different scenes and load each scene depending on user selection.

**Comment by churbis** [comment]
It’s common that AAA games also have a “loopback server” and run the entire single player game through “server” code that runs locally. This allows for code reuse and for listen servers in the clients.

**Comment by asyasmi** [comment]
Hi @SupinePandora43, 

Sorry for such a long response from us.  My name is Anastasia, I’m a software developer in test engineer in Networking team. As a part of the old issues review and closure procedure, I’ve looked through this issue. 

I'd second @adammpolak, I'd suggest initialization of DefaultWorld depending on a loaded scene you want to use for Single- and MultiPlayer. 

Closing this issue, but in case of any additional questions/issues - please file a bug using Unity Bug reporter. If you need further help, please contact us on the [forum](https://forum.unity.com/threads/dots-multiplayer-discussion.694669/page-2). 
Thanks, Anastasia
