### ISSUE TITLE
i cant find unity transport and netcode in package manager(unity 2019.2..8f1

### ISSUE THREAD

**Issue by virtouso** [Unity-Technologies/multiplayer#88]
a ticked for previous packagees but i didnt find any of them. a large list of packages but there is non of these packages

**Comment by virtouso** [comment]
i updated to 2019.3.9f and now i have them. dont know why they are ommited in previous versions

**Comment by adammpolak** [comment]
@virtouso have you selected "Show preview packages"?

It is in the "advanced" dropdown in the package manager window

**Comment by Brystephor** [comment]
I also cannot find unity transport or netcode package in the package manner. Yes I have selected "Show preview packages" as well. 

version: 2019.2.7f
os: windows 10

**Comment by asyasmi** [comment]
Hi to all,

Sorry for such a long response from us. My name is Anastasia, I’m a software developer in test engineer in Networking team. As a part of the old issues review and closure procedure, I’ve looked through this issue.

I've transferred this issue to Package manager team. I've checked using Version 2019.3.15f1 (49593feec2a2) and it works fine.
But in case, you can manually add dependencies to `manifest.json`:

```
   ...
   "com.unity.netcode": "0.2.0-preview.5",
   "com.unity.transport": "0.3.1-preview.4",
   ...
```

and they will appear in Package Manager also.

Closing this issue, but in case of any additional questions/issues - please file a bug using Unity Bug reporter.
Thanks, Anastasia
