### ISSUE TITLE
Transport incompatible with Collection 0.9.0

### ISSUE THREAD

**Issue by chatrat12** [Unity-Technologies/multiplayer#92]
From [Collections Change Log](https://docs.unity3d.com/Packages/com.unity.collections@0.9/changelog/CHANGELOG.html) 0.9.0 May 25th:

**Removed**
> Removed expired APIs for `UnsafeHashMap.Length`
> Removed expired APIs for `NativeHashMap.Length`

Latest version of Transport still calls `NativeHashMap.Length`. I believe it should now be calling `NativeHashMap.Count()`

This causes Unity to throw compile errors :O
![image](https://user-images.githubusercontent.com/251682/83304574-17547500-a1cd-11ea-9c1f-df4e7b0495a2.png)

The errors went away when I manually updated IPCManager.cs

**Comment by chatrat12** [comment]
Looks like NetCode also needs to be updated to be compatible with the latest Entities package. It calls `ArchetypeChunk.GetComponentVersion` instead of `ArchetypeChunk.GetChangeVersion`.

After I manually fixed that I get the following error when entering play mode

```
InvalidOperationException: Group of type Unity.NetCode.ClientSimulationSystemGroup has not been created, either the derived class forgot to call base.OnCreate(), or it has been destroyed
Unity.Entities.ComponentSystemGroup.CheckCreated () (at Library/PackageCache/com.unity.entities@0.11.0-preview.7/Unity.Entities/ComponentSystemGroup.cs:67)
Unity.Entities.ComponentSystemGroup.AddSystemToUpdateList (Unity.Entities.ComponentSystemBase sys) (at Library/PackageCache/com.unity.entities@0.11.0-preview.7/Unity.Entities/ComponentSystemGroup.cs:72)
Unity.NetCode.ClientServerBootstrap.CreateClientWorld (Unity.Entities.World defaultWorld, System.String name) (at Library/PackageCache/com.unity.netcode@0.1.0-preview.6/Runtime/ClientServerWorld/ClientServerBootstrap.cs:86)
Unity.NetCode.ClientServerBootstrap.Initialize (System.String defaultWorldName) (at Library/PackageCache/com.unity.netcode@0.1.0-preview.6/Runtime/ClientServerWorld/ClientServerBootstrap.cs:51)
Unity.Entities.DefaultWorldInitialization.Initialize (System.String defaultWorldName, System.Boolean editorWorld) (at Library/PackageCache/com.unity.entities@0.11.0-preview.7/Unity.Entities.Hybrid/Injection/DefaultWorldInitialization.cs:97)
Unity.Entities.AutomaticWorldBootstrap.Initialize () (at Library/PackageCache/com.unity.entities@0.11.0-preview.7/Unity.Entities.Hybrid/Injection/AutomaticWorldBootstrap.cs:15)
```

Seems like these packages need some upkeep :(

**Comment by sietse85** [comment]
> From [Collections Change Log](https://docs.unity3d.com/Packages/com.unity.collections@0.9/changelog/CHANGELOG.html) 0.9.0 May 25th:
> 
> **Removed**
> 
> > Removed expired APIs for `UnsafeHashMap.Length`
> > Removed expired APIs for `NativeHashMap.Length`
> 
> Latest version of Transport still calls `NativeHashMap.Length`. I believe it should now be calling `NativeHashMap.Count()`
> 
> This causes Unity to throw compile errors :O
> ![image](https://user-images.githubusercontent.com/251682/83304574-17547500-a1cd-11ea-9c1f-df4e7b0495a2.png)
> 
> The errors went away when I manually updated IPCManager.cs

Same problem here, how did you manually update it?

**Comment by asyasmi** [comment]
Hi 

Sorry for such a long response from us.  My name is Anastasia, I’m a software developer in test engineer in Networking team. As a part of the old issues review and closure procedure, I’ve looked through this issue. 

That's right, Collections package upgrade had breaking changes. Please update to the latest version, it's fixed there: 
 ```
"com.unity.netcode": "0.2.0-preview.5",
"com.unity.transport": "0.3.1-preview.4"
....
"com.unity.collections": "0.9.0-preview.5"
```

Closing this issue, but in case of any additional questions/issues - please file a bug using Unity Bug reporter.
Thanks, Anastasia
