### ISSUE TITLE
Unable to Import Unity Transport package on Unity 2019.3.15f1

### ISSUE THREAD

**Issue by Sleepybear** [Unity-Technologies/multiplayer#93]
I get the following error:
```
Library\PackageCache\com.unity.2d.animation@3.2.2\Runtime\TransformAccessJob.cs(196,62): error CS1061: 'NativeHashMap<int, TransformAccessJob.TransformData>' does not contain a definition for 'Length' and no accessible extension method 'Length' accepting a first argument of type 'NativeHashMap<int, TransformAccessJob.TransformData>' could be found (are you missing a using directive or an assembly reference?)
```
Seems to be an issue between the Collections package and the Unity 2D Animation package?

**Comment by Sleepybear** [comment]
It appears to be particularly a conflict with the Collections  0.9.0 - preview 5 build that causes the issue.

**Comment by asyasmi** [comment]
Hi @Sleepybear, 

Sorry for such a long response from us.  My name is Anastasia, I’m a software developer in test engineer in Networking team. As a part of the old issues review and closure procedure, I’ve looked through this issue. 

I'm not sure Networking packages have a lot to do with Collections or Animation 2D packages, and I've tried to reproduce it bu for me it works with no errors on: 

```
2d animation 3.2.3
Collection 0.9.9
Transport 0.3.1
Netcode 0.2.0
```

Closing this issue, but in case of any additional questions/issues or you're still experiencing this  - please file a bug using Unity Bug reporter.
Thanks, Anastasia
